// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKWi-EGsboGYFXepyKeeXTBVNCJKzHIM',
    appId: '1:225985776443:web:515081b95bc2f9dc11c51e',
    messagingSenderId: '225985776443',
    projectId: 'spoonacular-5ce74',
    authDomain: 'spoonacular-5ce74.firebaseapp.com',
    storageBucket: 'spoonacular-5ce74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8RLxtoOz2HhYu5zKur8i2tDlYR9so7uI',
    appId: '1:225985776443:android:860cf0b4c7863bfb11c51e',
    messagingSenderId: '225985776443',
    projectId: 'spoonacular-5ce74',
    storageBucket: 'spoonacular-5ce74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3HCKVMdvZyfUX0N6vJzhAEdWQMTqKFSw',
    appId: '1:225985776443:ios:89b0d7a8672ca79911c51e',
    messagingSenderId: '225985776443',
    projectId: 'spoonacular-5ce74',
    storageBucket: 'spoonacular-5ce74.appspot.com',
    iosBundleId: 'com.example.spoonacular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3HCKVMdvZyfUX0N6vJzhAEdWQMTqKFSw',
    appId: '1:225985776443:ios:89b0d7a8672ca79911c51e',
    messagingSenderId: '225985776443',
    projectId: 'spoonacular-5ce74',
    storageBucket: 'spoonacular-5ce74.appspot.com',
    iosBundleId: 'com.example.spoonacular',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASKWi-EGsboGYFXepyKeeXTBVNCJKzHIM',
    appId: '1:225985776443:web:2f951c5576dacbaf11c51e',
    messagingSenderId: '225985776443',
    projectId: 'spoonacular-5ce74',
    authDomain: 'spoonacular-5ce74.firebaseapp.com',
    storageBucket: 'spoonacular-5ce74.appspot.com',
  );
}
