name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Set up Android SDK
        run: |
          echo "sdk.dir=$ANDROID_HOME" > $GITHUB_WORKSPACE/local.properties
        env:
          ANDROID_HOME: /Users/runner/Library/Android/sdk

      - name: Install dependencies
        run: flutter pub get

      - name: Remove Flutter lock file if exists
        run: rm -f $HOME/.flutter/flutter.lock

      - name: Run tests
        run: flutter test

      - name: Build android apk and appBundle
        run: flutter build apk

      - name: Build ios
        run: flutter build ios --release --no-codesign
